language: android
android:
  components:
    - build-tools-23.0.1
    # The SDK version used to compile your project
    - android-23
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - android-sdk-license-.+