language: android
android:
  components:
    - build-tools-23.0.1
    # The SDK version used to compile your project
    - android-23
    - extra-android-support
    - extra-android-m2repository
    - sys-img-x86-android-17
  licenses:
    - android-sdk-license-.+

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &